### PR TITLE
#53_Recreated_the_HomePage

### PR DESCRIPTION
**Pull request by imsachinsingh10**
This PR is under #53 which is under SWoC'21

All the Necessary changes has been made except for few content which is left for Admin to change it, Specially in the Features section.

Few Animations have been applied in the home screen, features section and Footer.
i will be attaching the pictures to show how it looks now.

### CODE REVIEW

**Comment by imsachinsingh10** [comment]
Screenshot (61)
Screenshot (62)
Screenshot (63)
Screenshot (64)
Screenshot (65)
Screenshot (66)
Screenshot (67)
Screenshot (68)
Screenshot (69)
Screenshot (70)
Screenshot (71)

**Comment by imsachinsingh10** [comment]
@Harshita248 Sorry I forgot to change the Dark color footer to light theme one, 
If this is made a Successful PR then I will add it under Footer issue, because then it will have No Conflict issues

**Comment by Harshita248** [comment]
No problem

**Comment by imsachinsingh10** [comment]
Ma'am Please Label this pull request under SWoC because then only it will be considered as a successful PR under SWoC

**Pull request merged**
