### PR TITLE
Completing issues 16 and 22

### LINKED ISSUE #16: Add some good illustrations to the images folder (relevant to the website) to be used in the website .
Please refer to trello.com

### LINKED ISSUE #22: Add similar styling to both the login page as well as the index page.
Styling in the sense the illustration in the background and the header and footer

### PR DESCRIPTION
**Pull request by UMuktesh**
Added .svg illustrations necessary for index and login page
Added similar styling to index and login page
This closes #22 and fixes #16

### CODE REVIEW

**Comment by UMuktesh** [comment]
Sign In Page:
image
image
Admin Login Form Page:
image
image

**Comment by Harshita248** [comment]
please do separate pull requests for separate issues otherwise it will be difficult for awarding points. For now I'm merging the pull request and awarding you 5 points for the illustrations issue #16  But then 25 points will be given only if you style the index page in a similar way. From now on please do separate pull requests for separate issues listed. @UMuktesh

**Comment by Harshita248** [comment]
give @UMuktesh 5 points

**Comment by UMuktesh** [comment]
@Harshita248 Both index and login page are similarly styled. The 2nd and 4th image are media query. Check the screenshots once. Also I added illustrations for #22 as they are needed so I made a single PR. I'll mind that next time.

**Comment by Harshita248** [comment]
Okay I have checked it's alright @UMuktesh

**Comment by Harshita248** [comment]
give @UMuktesh 25 points

**Pull request merged**
